# Generated by Django 4.1.4 on 2022-12-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosalind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.CharField(max_length=100)),
                ('teachers_schedule', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='rosalind_teacher',
        ),
    ]
