# Generated by Django 4.1.4 on 2022-12-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosalind', '0002_teacherschedule_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
