# Generated by Django 4.1.4 on 2022-12-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosalind', '0003_alter_teacher_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='rosalind_teacher',
        ),
        migrations.AlterModelTable(
            name='teacherschedule',
            table='rosalind_teacherschedule',
        ),
    ]
